version: 0.0
os: linux
files:
  - source: /
    destination: destination: /home/ec2-user/apps/news
#hooks:
#  ApplicationStop:
#    - location: deploy_scripts/ApplicationStop.sh
#      timeout: 300
#      runas: root
#  BeforeInstall:
#    - location: deploy_scripts/BeforeInstall.sh
#      timeout: 300
#      runas: root
#  AfterInstall:
#    - location: deploy_scripts/AfterInstall.sh
#      timeout: 300
#      runas: root
#  ApplicationStart:
#    - location: deploy_scripts/ApplicationStart.sh
#      timeout: 300
#      runas: root
